### ISSUE TITLE
How did you calculate the FID

### ISSUE THREAD

**Issue by loexwe** [zhaobozb/layout2im#1]
Hi, thanks for the fantastic work and sharing the code. I run the pertrained model, and calculated the FID, but did not get FID as your cvpr version (31 for vg, I got 39). Did I do something wrong? How many images did you use for calculating FID? What about image size?

**Comment by zhaobozb** [comment]
Hi loexwe, thank you for your feedback. After inspecting it, I found that the reported FID score of 31.25 for VG is computed from a model different from the released one, and other metrics are computed from the released one. Using the released model on VG, I got an FID score of 40.07, which is close to what you got. Sorry for the confusion, and I will make a revision of our paper.
