### ISSUE TITLE
How did you get your is score and fid?

### ISSUE THREAD

**Issue by echooooHsu** [zhaobozb/layout2im#2]
Hi zhaobozb, thanks for giving the code and the awesome work. When i run the code, i got some problems about metrics.  When i trying to run the code that you are describing in the github. I followed the most your description except the batch_size and iteration time ,i set the batch_size to 16 and iteration 150000, the GPU i used is 1080Ti, but unfortunately my result is not matching with yours in the paper.While you tested the IS score 9.1 points for me the result is only have 1.2. Did i got something wrong?Can you give me the metrics code or do you have some advice for me how i can get a bigger result?

**Comment by zhaobozb** [comment]
Hi echoooooHsu,

Thanks for your interests for our work.

We use this [code](https://github.com/zhaobozb/layout2im/files/3572029/compute.inception.score.zip) to compute `Inception Score`, and this [code](https://github.com/bioinf-jku/TTUR) to compute `FID`.

Please feel free to contact me if you have any questions.

Cheers,
Bo

**Comment by echooooHsu** [comment]
OK, I get it,THanks
