### ISSUE TITLE
How did you get your IS and FID

### ISSUE THREAD

**Issue by jiangtianling** [zhaobozb/layout2im#6]
Hi zhaobozb, thanks for giving the code and the awesome work. When i run the code, i got some problems about metrics. When i trying to run the code that you are describing in the github. I followed the whole your description about hyperparameters . I tested your trained models on 2080Ti and 1080Ti respectively, but unfortunately my result is not matching with yours in the paper.While you tested the IS score and FID are 9.1 points  and 38.14 on COCO-stuff for me the result are only have 9.1 and 42.8. The IS score is 8.1 points on  VG dataset for me the result is 7.8. Did i got something wrong?Do you have some advice for me how i can get a bigger result?
Thanks, best wishes!

**Comment by zhaobozb** [comment]
Hi jiangtianling,

Thanks for your interests for our work.

We use this [code](https://github.com/zhaobozb/layout2im/files/3572029/compute.inception.score.zip) to compute `Inception Score`, and this [code](https://github.com/bioinf-jku/TTUR) to compute `FID`.

Please feel free to contact me if you have any questions.

Cheers,
Bo
